application: hongryweb
version: 1
runtime: python
api_version: 1

handlers:
- url: /css
  static_dir: css
- url: /js
  static_dir: js
- url: /img
  static_dir: img
- url: /images
  static_dir: img
- url: /es
  static_dir: hongrymx2  
- url: .*
  script: lib/run_server.py
