application: hongryweb
version: 1
runtime: python
api_version: 1

handlers:
- url: /css
  static_dir: static/css
- url: /js
  static_dir: static/js
- url: /img
  static_dir: static/img
- url: /images
  static_dir: static/img
- url: /es
  static_dir: static/es 
- url: .*
  script: lib/run_server.py
